server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.1.133:3306/public?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
