#   服务信息配置
server:
  port: 18080
#  address: 10.147.20.132
spring:
  #   应用相关设置
  application:
    name: gateway-server
    deploy: dev
    version: v1
  profiles:
    active: dev
  # nacos相关设置
  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: basic
    nacos:
      discovery:
        #        server-addr: 172.23.255.221:8848
        server-addr: 192.168.1.136:8848
        namespace: DEMO
        group: ${spring.application.deploy}
        username: nacos
        password: nacos
        service: ${spring.application.name}
        register-enabled: true
        ip: 192.168.199.116
    #        网关相关配置
    gateway:
      enabled: true
      routes:
        - id: user-server
#          uri: http://localhost:18081
          uri: lb://user-server
          predicates:
            - Path=/user-server/**
          filters:
            - StripPrefix=1
        - id: msg-server
          uri: lb://msg-server
          predicates:
            - Path=/msg-server/**
          filters:
            - StripPrefix=1
        - id: chat-server
          uri: lb://gpt-server
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000

