# 服务信息配置
server:
  port: 18083
spring:
 #   应用相关设置
  application:
    name: gpt-server
#    大模型设置
  ai:
    ollama:
      chat:
#        model: deepseek-r1:8b
        model: huihui_ai/deepseek-r1-abliterated:14b
      base-url: http://localhost:11434