version: '3.8'

services:
  kafka2:
    image: apache/kafka:4.0.0 # 请根据实际 Kafka 4.0 版本替换
    container_name: kafka2-broker
    ports:
      - "9192:9092" # 使用不同的 Broker 端口
      - "10099:9999" # 使用不同的 JMX 端口 (可选)
    environment:
      KAFKA_NODE_ID: 2 # 使用不同的节点 ID
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka2:9193 # 使用不同的 Controller 端口
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9192,CONTROLLER://0.0.0.0:9193 # 使用不同的监听端口
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.136:9192 # 使用指定的 IP 地址和不同的 Broker 端口
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_PROTOCOL: eager
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data2 # 使用不同的数据目录
    volumes:
      - kafka2_data:/var/lib/kafka/data2
    restart: on-failure

volumes:
  kafka2_data: