#   服务信息配置
server:
  port: 18081
spring:
  #   应用相关设置
  application:
    name: user-server
  #    数据库连接配置
  datasource:
    url: jdbc:mysql://192.168.1.133:3306/public?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  #     rabbit消息队列配置
  rabbitmq:
    port: 5672
    host: 192.168.1.136
    username: guest
    password: guest
  artemis:
    embedded:
      queues: queue-hello

  main:
    allow-circular-references: true
  # ====   nacos相关配置
  cloud:
    nacos:
      discovery:
        #        server-addr: 172.23.255.221:8848
        server-addr: 192.168.1.136:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        service: user-server
        register-enabled: true
        #        ip: 172.23.255.221
        ip: 192.168.1.136