server:
  port: 18081
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://192.168.1.133:3306/public?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    host: 192.168.1.136
    username: guest
    password: guest
  artemis:
    embedded:
      queues: queue-hello

  main:
    allow-circular-references: true

  cloud:
    nacos:
      discovery:
        server-addr: 172.23.255.221:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        service: user-server
        register-enabled: true
        ip: 172.23.255.221